spring:
  main:
    banner-mode: off
  application:
    name: safenotes
  datasource:
    username: safenotes
    password: safenotes
    url: jdbc:postgresql://localhost:5432/safenotesdb
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
     ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
  issuer: safenotes
  expires-in: 240
  refresh:
    expires-in: 2592000
