services:
  db:
    image: postgres:16-alpine
    container_name: safenotes-postgres
    environment:
      POSTGRES_USER: safenotes
      POSTGRES_PASSWORD: safenotes
      POSTGRES_DB: safenotesdb
    ports:
      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: safenotes-redis
    ports:
      - "6379:6379"

volumes:
  db-data: